name: Update readme

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install

      - name: Generate readme
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - name: Check Git Status
        run: git status

      - name: Force Add & Commit
        run: |
          git config --global user.name "Jin Hyung Park"
          git config --global user.email "hophfg@yahoo.co.kr"
          git add --all
          git commit -m "Auto updating chat.svg"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: IDPLab-chosun
          author_email: idplab4127@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
