name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate ENV Variables
        run: |
          if [ -z "$WEATHER_API_KEY" ]; then
            echo "Missing WEATHER_API_KEY"
            exit 1
          fi
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

      - name: Run build-svg.js
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - name: Run tests
        run: |
          npm test || (echo "Tests failed!" && exit 1)

      - name: Install dependencies
        run: npm ci

